import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);

const groups = require("unicode-emoji-json/data-by-group.json");

// Emoji render through the Twemoji colour font (see app.css). unicode-emoji-json
// tracks a newer Unicode than the font ships, so a handful of recent sequences
// (head shaking, walking-facing-right, ...) have no single glyph and the browser
// splits them into their parts. Keep only what the font draws as one glyph.
const fontkit = require("fontkit");
const font = fontkit.openSync(
  join(dirname(require.resolve("twemoji-colr-font/package.json")), "twemoji.woff2"),
);
const renderable = (emoji) => {
  const { glyphs } = font.layout(emoji);
  return glyphs.length === 1 && glyphs[0].id !== 0;
};

const iamcal = require("emojibase-data/en/shortcodes/iamcal.json");
const github = require("emojibase-data/en/shortcodes/github.json");
const emojibase = require("emojibase-data/en/data.json");

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "../src/lib/emoji/data.ts");
// The server has to validate a reaction against the same set the picker offers,
// so the bare glyphs go to the shared package as well.
const sharedOut = join(here, "../../shared/src/emoji-glyphs.ts");

const HIDDEN_GROUPS = new Set(["Flags"]);

// The datasets disagree on carrying FE0F, so it cannot be part of the join key.
const hexcode = (char) =>
  [...char]
    .map((c) => c.codePointAt(0).toString(16).toUpperCase().padStart(4, "0"))
    .filter((h) => h !== "FE0F")
    .join("-");

const list = (v) => (Array.isArray(v) ? v : v ? [v] : []);
const normalize = (s) =>
  s
    .toLowerCase()
    .replace(/[\s-]+/g, "_")
    .replace(/[^\w+]/g, "");

const tagsByHex = new Map();
for (const entry of emojibase) {
  tagsByHex.set(hexcode(entry.emoji), entry.tags ?? []);
}

const shortcodesByHex = new Map();
for (const source of [iamcal, github]) {
  for (const [hex, value] of Object.entries(source)) {
    const key = hexcode(
      String.fromCodePoint(...hex.split("-").map((h) => parseInt(h, 16))),
    );
    const existing = shortcodesByHex.get(key) ?? [];
    shortcodesByHex.set(key, [...existing, ...list(value)]);
  }
}

let missingShortcode = 0;

const groupEntries = groups.map((group) => ({
  name: group.name,
  hidden: HIDDEN_GROUPS.has(group.name),
  emojis: group.emojis
    .filter((e) => renderable(e.emoji))
    .map((e) => {
      const hex = hexcode(e.emoji);
      const aliases = [...new Set(shortcodesByHex.get(hex) ?? [])].map(normalize);
      if (!aliases.length) missingShortcode++;

      const primary = aliases[0] ?? e.slug;

      const names = [...new Set([...aliases, e.slug])].filter((n) => n && n !== primary);

      const tags = [...new Set((tagsByHex.get(hex) ?? []).map(normalize))].filter(
        (t) => t && t !== primary && !names.includes(t),
      );

      return [e.emoji, primary, names.join(" "), tags.join(" ")];
    }),
}));

const total = groupEntries.reduce((n, g) => n + g.emojis.length, 0);
const dropped = groups.reduce((n, g) => n + g.emojis.length, 0) - total;

const body = groupEntries
  .map(
    (g) =>
      `  {\n    name: ${JSON.stringify(g.name)},\n    hidden: ${g.hidden},\n    emojis: [\n${g.emojis
        .map((e) => `      [${e.map((v) => JSON.stringify(v)).join(", ")}],`)
        .join("\n")}\n    ],\n  },`,
  )
  .join("\n");

writeFileSync(
  out,
  `// Generated by scripts/generate-emoji.js. Do not edit.
// Regenerate with: npm --workspace client run emoji:gen
//
// Structure and ordering from unicode-emoji-json; shortcodes from emojibase's
// iamcal (Slack) and github sets, which are the names Discord users type.

/** \`names\` and \`tags\` are space separated. \`tags\` rank below \`names\` in
 *  search, so \`:smile\` offers 😄 before a tag match. */
export type EmojiEntry = readonly [
  emoji: string,
  shortcode: string,
  names: string,
  tags: string,
];

export type EmojiGroup = {
  readonly name: string;
  /** Kept out of the picker grid, still reachable through search. */
  readonly hidden: boolean;
  readonly emojis: readonly EmojiEntry[];
};

/** ${total} emoji across ${groupEntries.length} groups. */
export const EMOJI_GROUPS: readonly EmojiGroup[] = [
${body}
];
`,
);

// One space-separated string rather than an array of quoted strings: no emoji
// contains a space, and it saves several kilobytes in a list this long.
const glyphs = groupEntries.flatMap((g) => g.emojis.map(([emoji]) => emoji));

writeFileSync(
  sharedOut,
  `// Generated by client/scripts/generate-emoji.js. Do not edit.
// Regenerate with: npm --workspace client run emoji:gen

/** The ${glyphs.length} emoji the Twemoji colour font draws as a single glyph,
 *  which is exactly the set the picker offers. Anything outside it renders as a
 *  tofu box for every reader, so it is not a set anyone may react with. */
export const EMOJI_GLYPHS: readonly string[] =
  ${JSON.stringify(glyphs.join(" "))}.split(" ");
`,
);

execFileSync(
  process.execPath,
  [require.resolve("prettier/bin/prettier.cjs"), "--write", out, sharedOut],
  {
    stdio: "inherit",
  },
);

console.log(`wrote ${total} emoji to ${out}`);
console.log(`wrote ${glyphs.length} glyphs to ${sharedOut}`);
if (dropped) console.log(`${dropped} dropped: no single glyph in the Twemoji font`);
if (missingShortcode)
  console.log(`${missingShortcode} had no Slack/GitHub shortcode, kept CLDR slug`);
