#!/usr/bin/env sh
# ccchat installer. Sets up a community in one command:
#
#   curl -fsSL https://raw.githubusercontent.com/OWNER/ccchat/main/install.sh | sh
#
# It asks for one thing (your domain), generates the secrets nobody should ever
# have to invent themselves, and starts the stack. Everything else — the
# community name, your owner account, the invite code — happens in the browser.
#
# Run it again any time to upgrade: it pulls the latest image and keeps your .env.

set -eu

REPO="${CCCHAT_REPO:-OWNER/ccchat}" # TODO(repo): set to your GitHub owner/name
BRANCH="${CCCHAT_BRANCH:-main}"
RAW="https://raw.githubusercontent.com/${REPO}/${BRANCH}"
DIR="${CCCHAT_DIR:-$HOME/ccchat}"

say() { printf '\033[1;36m==>\033[0m %s\n' "$1"; }
die() { printf '\033[1;31mError:\033[0m %s\n' "$1" >&2; exit 1; }

# ── prerequisites ────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "The Docker Compose plugin is missing. See https://docs.docker.com/compose/install/"
docker info >/dev/null 2>&1 || die "Cannot talk to the Docker daemon. Is it running, and is your user in the 'docker' group?"

mkdir -p "$DIR"
cd "$DIR"

# ── config files ─────────────────────────────────────────────────────────────
# Skipped when running from a git clone, which already has them.
for f in docker-compose.yml Caddyfile livekit.yaml; do
  if [ ! -f "$f" ]; then
    say "Fetching $f"
    curl -fsSL "$RAW/$f" -o "$f" || die "Could not download $f from $RAW"
  fi
done

# ── secrets + domain ─────────────────────────────────────────────────────────
if [ -f .env ]; then
  say "Reusing the existing .env (delete it to start over)"
else
  # The domain is the ONLY thing we need from a human. It must already point at
  # this machine's public IP, or Let's Encrypt cannot issue a certificate.
  if [ -n "${CCCHAT_DOMAIN:-}" ]; then
    domain="$CCCHAT_DOMAIN"
  else
    printf 'Domain for your community (e.g. chat.example.com): '
    read -r domain </dev/tty
  fi
  [ -n "$domain" ] || die "A domain is required. Voice needs HTTPS, and HTTPS needs a name."

  # Never seen by a human, never typed by a human.
  secret=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

  cat > .env <<EOF
# Generated by install.sh — you should not need to edit this.
CCCHAT_DOMAIN=$domain
CCCHAT_IMAGE=ghcr.io/$REPO:latest
LIVEKIT_API_KEY=ccchat
LIVEKIT_API_SECRET=$secret
EOF
  chmod 600 .env
  say "Wrote .env (domain: $domain, LiveKit secret generated)"
fi

# ── go ───────────────────────────────────────────────────────────────────────
say "Pulling images"
docker compose pull

say "Starting ccchat"
docker compose up -d

domain=$(grep '^CCCHAT_DOMAIN=' .env | cut -d= -f2-)

cat <<EOF

  ccchat is starting at  https://$domain

  Open it in a browser to name your community and create your owner account.
  You will get an invite code to share with your friends.

  The first load can take a minute while Caddy obtains a TLS certificate.

  Make sure your router/firewall forwards:
    80/tcp, 443/tcp   the app (80 is needed to issue the certificate)
    7882/udp          voice media  <-- without this, voice will not connect

  Your data lives in $DIR/data — back that folder up.
  Logs:    docker compose -f $DIR/docker-compose.yml logs -f
  Upgrade: re-run this script.

EOF
