#Requires -Version 5.1
<#
.SYNOPSIS
  ccchat installer for Windows. The PowerShell twin of install.sh.

.DESCRIPTION
  Sets up a community in one command:

    irm https://raw.githubusercontent.com/lucien-n/kit-ccchat/main/install.ps1 | iex

  It asks for one thing (your domain), generates the secrets nobody should have
  to invent, and starts the stack. The community name, your owner account and
  the invite code are all created afterwards in the browser.

  Run it again any time to upgrade: it pulls the latest image and keeps your .env.

  HEADS UP: voice does NOT work under Docker Desktop on Windows — its network
  layer cannot pass WebRTC UDP media (a documented Docker Desktop limitation,
  not a ccchat bug). Text chat is fine. For working voice, host on a Linux box
  (see install.sh) or run LiveKit natively (see the README).
#>

[CmdletBinding()]
param(
  # Skip the prompt by passing the domain up front (or set $env:CCCHAT_DOMAIN).
  [string]$Domain = $env:CCCHAT_DOMAIN,
  # Where to install. Defaults to %USERPROFILE%\ccchat (or $env:CCCHAT_DIR).
  [string]$InstallDir = $(if ($env:CCCHAT_DIR) { $env:CCCHAT_DIR } else { Join-Path $HOME 'ccchat' })
)

$ErrorActionPreference = 'Stop'

$Repo   = if ($env:CCCHAT_REPO)   { $env:CCCHAT_REPO }   else { 'lucien-n/kit-ccchat' }
$Branch = if ($env:CCCHAT_BRANCH) { $env:CCCHAT_BRANCH } else { 'main' }
$Raw    = "https://raw.githubusercontent.com/$Repo/$Branch"

function Say  { param([string]$m) Write-Host "==> $m" -ForegroundColor Cyan }
function Die  { param([string]$m) Write-Host "Error: $m" -ForegroundColor Red; exit 1 }

# ── prerequisites ────────────────────────────────────────────────────────────
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Die 'Docker is not installed. See https://docs.docker.com/desktop/install/windows-install/'
}
try { docker compose version | Out-Null } catch {
  Die 'The Docker Compose plugin is missing. It ships with Docker Desktop — is Docker Desktop installed?'
}
try { docker info | Out-Null } catch {
  Die 'Cannot talk to the Docker daemon. Is Docker Desktop running?'
}

Write-Host ''
Write-Host 'Note: voice will not work under Docker Desktop on Windows (WebRTC UDP' -ForegroundColor Yellow
Write-Host '      cannot pass through it). Text chat works. Host on Linux for voice.' -ForegroundColor Yellow
Write-Host ''

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Set-Location $InstallDir

# ── config files ─────────────────────────────────────────────────────────────
# Skipped when running from a git clone, which already has them.
foreach ($f in 'docker-compose.yml', 'Caddyfile', 'livekit.yaml') {
  if (-not (Test-Path $f)) {
    Say "Fetching $f"
    try { Invoke-WebRequest -Uri "$Raw/$f" -OutFile $f -UseBasicParsing }
    catch { Die "Could not download $f from $Raw" }
  }
}

# ── secrets + domain ─────────────────────────────────────────────────────────
if (Test-Path '.env') {
  Say 'Reusing the existing .env (delete it to start over)'
} else {
  # The domain is the ONLY thing we need from a human. It must already point at
  # this machine's public IP, or Let's Encrypt cannot issue a certificate.
  if (-not $Domain) {
    $Domain = Read-Host 'Domain for your community (e.g. chat.example.com)'
  }
  if (-not $Domain) { Die 'A domain is required. Voice needs HTTPS, and HTTPS needs a name.' }

  # Never seen by a human, never typed by a human. 32 random bytes as hex.
  $bytes = [byte[]]::new(32)
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  $secret = -join ($bytes | ForEach-Object { $_.ToString('x2') })

  # Write UTF-8 without BOM: docker compose chokes on a BOM in an env file.
  $envBody = @"
# Generated by install.ps1 — you should not need to edit this.
CCCHAT_DOMAIN=$Domain
CCCHAT_IMAGE=ghcr.io/$Repo`:latest
LIVEKIT_API_KEY=ccchat
LIVEKIT_API_SECRET=$secret
"@
  [System.IO.File]::WriteAllText((Join-Path $InstallDir '.env'), $envBody + "`n", (New-Object System.Text.UTF8Encoding $false))
  Say "Wrote .env (domain: $Domain, LiveKit secret generated)"
}

# ── go ───────────────────────────────────────────────────────────────────────
Say 'Pulling images'
docker compose pull

Say 'Starting ccchat'
docker compose up -d

$Domain = (Select-String -Path '.env' -Pattern '^CCCHAT_DOMAIN=(.*)$').Matches[0].Groups[1].Value

Write-Host ''
Write-Host "  ccchat is starting at  https://$Domain" -ForegroundColor Green
Write-Host ''
Write-Host '  Open it in a browser to name your community and create your owner account.'
Write-Host '  You will get an invite code to share with your friends.'
Write-Host ''
Write-Host '  The first load can take a minute while Caddy obtains a TLS certificate.'
Write-Host ''
Write-Host '  Make sure your router/firewall forwards:'
Write-Host '    80/tcp, 443/tcp   the app (80 is needed to issue the certificate)'
Write-Host '    7882/udp          voice media  <-- Docker Desktop on Windows cannot pass this'
Write-Host ''
Write-Host "  Your data lives in $InstallDir\data — back that folder up."
Write-Host "  Logs:    docker compose -f `"$InstallDir\docker-compose.yml`" logs -f"
Write-Host '  Upgrade: re-run this script.'
Write-Host ''
